### ISSUE TITLE
Implement Across Step

### ISSUE THREAD

**Issue by kcbimonte** [kcbimonte/Concourse-Pipeline-SDK#24]
# BLUF
As a developer, I want to implement the across step so that I can take steps to developing dynamic pipelines that span an array of resources.

# Description
The across step is made up of two parts: 
```yaml
across:
- description: List of Across Vars to loop over
  type: List<across_var>
  required: false
fail_fast:
  description: The across step will fail when any sub-step fails
  type: boolean
  required: false
```

An across variable is defined as the following:
```yaml
var:
  description: Name of the variable
  type: identifier
  required: true
values: 
- description: List of values to iterate over
  type: List<value>
  required: true
max_in_flight:
  description: Number of variables to run in parallel
  type: all | number
  required: false
```

# Restrictions

An across step cannot be used with a `get` or `put` step. An `AbstractAcrossStep` extending `AbstractStep` would solve this limitation.

# Resources

- [across Step Modifier | Concourse](https://concourse-ci.org/across-step.html)
